name: 'hello world'
description: 'test docker'
inputs:
  who-to-greet:
    description: 'who to  greet'
    required: true
    default: 'world'
output:
  time:
    description: 'time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ input.who-to-greet }}
