name: main
on: [push]

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest

    steps:
      - name: bianyi
        uses: action/checkout@v3
        shell: bash
        run: |
          ls;
          make -f Makefile;
