name: main
on: [push]

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: action/checkout@v3

      - name: cache files
        uses: action/cache@v3
        with:
          main.tar.gz

      - name: bianyi
        shell: bash
        run: make
