name: helloworld
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        env:
          github_token: ${{ secrets.token }}
      - uses: actions/checkout@v3
      - name: bianyi
        run:
          make -f Makefile

      - name: shangchuan
        uses: softprops/action-gh-release@v1
        with:
     #     #publish_dir: ./test
          files: ./main.tar.gz

