name: test
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: centos-latest
    steps:
        uses: actions/checkout@v3
      - name: bianyi
        run: 
          make -f Makefile

      - name: dabao
        run: tar cvf main.tar main

      - name: shangchuan
        uses: softprops/action-gh-release@v1
        with:
          files: ./main.tar
          github_token: ${{ secrets.token }}
