name: helloworld
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: bianyi
        run:
          make
      - name: shangchuan
        uses: softprops/action-gh-release@v1
        with:
          github_token: ${{ secrets.token }}
          publish_dir: ./test
          files: ./test/main.tar.gz

