name: helloworld
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: centos-latest
    steps:
      - name: bianyi
      - uses: actions/checkout@v3
        run:
          cd src/;make -f Makefile

      - name: dabao
      - uses: actions/checkout@v3
        run: cp src/main . ; tar cvf main.tar main

      - name: shangchuan
      - uses: actions/checkout@v3
        with:
          files: ./main.tar.gz
        env:
          github_token: ${{ secrets.token }}
