name: main
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: a job to say hello
    steps:
      - name: hello world action step
        id: hello
        uses: actions/helloworld-autopackage@v2
        with:
          who-to-greet: 'ten on test'

      - name: get the output time
        run: echo "the time was ${{ steps.hello.output.time}}"

